function updateProgress(iter_time, total_iters, t_start)

    persistent completed

    if isempty(completed)
        completed = 0;
    end

    completed = completed + 1;

    elapsed = toc(t_start);
    avg_time = elapsed / completed;
    remaining_secs = avg_time * (total_iters - completed);
    remaining_hours = remaining_secs / 3600;

    fprintf(['Completed %d/%d (%.1f%%) | ' ...
             'This Iter %.2fs | ' ...
             'Elapsed %.1fs | ' ...
             'Remaining %.2f hours\n'], ...
        completed, total_iters, ...
        100*completed/total_iters, ...
        iter_time, ...
        elapsed, ...
        remaining_hours);
end